[package]
name = "boost_algorithm"
description = "Boost C++ library boost_algorithm packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_algorithm"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_algorithm"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_array = { version = "0.1.0", path = "../boost_array" }
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_bind = { version = "0.1.0", path = "../boost_bind" }
boost_concept_check = { version = "0.1.0", path = "../boost_concept_check" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_core = { version = "0.1.0", path = "../boost_core" }
boost_exception = { version = "0.1.0", path = "../boost_exception" }
boost_function = { version = "0.1.0", path = "../boost_function" }
boost_iterator = { version = "0.1.0", path = "../boost_iterator" }
boost_mpl = { version = "0.1.0", path = "../boost_mpl" }
boost_range = { version = "0.1.0", path = "../boost_range" }
boost_regex = { version = "0.1.0", path = "../boost_regex" }
boost_static_assert = { version = "0.1.0", path = "../boost_static_assert" }
boost_throw_exception = { version = "0.1.0", path = "../boost_throw_exception" }
boost_tuple = { version = "0.1.0", path = "../boost_tuple" }
boost_type_traits = { version = "0.1.0", path = "../boost_type_traits" }
boost_unordered = { version = "0.1.0", path = "../boost_unordered" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
